#!/bin/sh

ADDON_NAME=hbunisentemp
ADDON_DIR=/usr/local/addons/$ADDON_NAME

mount -o remount,rw /

##########################################
### New device HB-UNI-Sen-TEMP-DS18B20 ###
##########################################
device="HB-UNI-Sen-TEMP-DS18B20"

### Copy new devices Files ###
cp -a firmware/rftypes/* /firmware/rftypes/

### Copy new images ###
cp -ar www/config/img/devices /www/config/img/

### Edit DEVDB.tcl ###
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert=""
devdescrInsert="$devdescrInsert HB-UNI-Sen-TEMP-DS18B20 {{50 \/config\/img\/devices\/50\/hb-uni-sen-temp-ds18b20_thumb.png} {250 \/config\/img\/devices\/250\/hb-uni-sen-temp-ds18b20.png}} "

if [ -z "`cat $devdescrFile | grep \"$device\"`" ]; then
	cp -a $devdescrFile $ADDON_DIR/DEVDB.tcl.hbunisentempsave
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

### Edit webui.js ###
webuiFile="/www/webui/webui.js"
webuiSearch="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"

webuiInsert="\n"
webuiInsert="$webuiInsert DEV_HIGHLIGHT['HB-UNI-Sen-TEMP-DS18B20'] = new Object();\n"
webuiInsert="$webuiInsert DEV_LIST.push('HB-UNI-Sen-TEMP-DS18B20');\n"
webuiInsert="$webuiInsert DEV_DESCRIPTION['HB-UNI-Sen-TEMP-DS18B20']='Universal 1..8x Temperatursensor DS18B20';\n"
webuiInsert="$webuiInsert DEV_PATHS['HB-UNI-Sen-TEMP-DS18B20'] = new Object();\n"
webuiInsert="$webuiInsert DEV_PATHS['HB-UNI-Sen-TEMP-DS18B20']['50'] = '\/config\/img\/devices\/50\/hb-uni-sen-temp-ds18b20_thumb.png';\n"
webuiInsert="$webuiInsert DEV_PATHS['HB-UNI-Sen-TEMP-DS18B20']['250'] = '\/config\/img\/devices\/250\/hb-uni-sen-temp-ds18b20.png';\n"

if [ -z "`cat $webuiFile | grep \"$device\"`" ]; then
	cp -a $webuiFile $ADDON_DIR/webui.js.hbunisentempsave
	sed -i "s/\($webuiSearch\)/\1$webuiInsert/g" $webuiFile
fi

sync

mount -o remount,ro /

touch $ADDON_DIR/installed