#!/bin/sh

NAME=hbunisentemp
DEVICE="HB-UNI-Sen-TEMP-DS18B20"
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log

ADDON_DIR=/usr/local/addons/${NAME}
WWW_DIR=/etc/config/addons/www/${NAME}
RCD_DIR=/usr/local/etc/config/rc.d

start() 
{
  echo 'Starting...'
  if [ ! -f ${ADDON_DIR}/installed ] || [ ! -f /firmware/rftypes/hb_unisen_temp.xml ]; then
    cd ${ADDON_DIR}
    ./install  > $LOGFILE 2> /dev/null & echo $!> $PIDFILE
  else
   echo "Nothing to do."
  fi
}

stop() 
{
  echo 'Stopped'
}

case "$1" in
start)
start
;;
stop)
stop
;;
uninstall)
    cd ${ADDON_DIR}
    ./uninstall  > $LOGFILE 2> /dev/null & echo $!> $PIDFILE
    cd /
    rm -rf $ADDON_DIR
    rm -rf $WWW_DIR
  ;;
  
restart)
stop
start
;;

info)
  echo "Info: <b>$DEVICE Addon</b><br>"
  echo "Info: <a href='https://github.com/jp112sdl/$DEVICE'>https://github.com/jp112sdl/$DEVICE</a>"
  echo "Version: $(cat ${ADDON_DIR}/VERSION)"
  echo "Name: $DEVICE"
  echo "Operations: uninstall"
  #echo "Config-Url: ${CONFIG_URL}"
  echo "Update: /addons/$NAME/update-check.cgi"
    ;;
	
*)
start
echo "Usage: $0 {start|stop|restart|uninstall}"
esac
